### ISSUE TITLE
Automated build

### ISSUE THREAD

**Issue by drewnoakes** [NetMQ/NetMQ.ReactiveExtensions#16]
AppVeyor makes it pretty easy to set up an automated build for a project:

https://ci.appveyor.com/project/drewnoakes/netmq-reactiveextensions

I'm not sure how this works given this repo is owned by an organisation. Hopefully it just works. Mostly I've found AppVeyor to just work.

Tasks:
- [x] add badges to the README to show the status of the build
- [x] verify that the build is run on PRs

**Comment by sharpe5** [comment]
Definitely agree on this one.

**Comment by sharpe5** [comment]
Just did a pull request, the build is definitely being run before it allows said pull request.

**Comment by drewnoakes** [comment]
If you're happy with the build, feel free to close this.

**Comment by sharpe5** [comment]
Just added the build badge. Once pull request #24 is merged (preferably by someone other than myself according to C4.1), we can close off this task.

Thanks ever so much!

**Comment by drewnoakes** [comment]
Looking good.
