### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by jaredthirsk** [NetMQ/NetMQ.ReactiveExtensions#33]
NetMQ was just made ready for .NET Core how about this library?

I am looking at using NetMQ for cross-platform SOA communications and I like Rx so it might be cool to have this library as well on Linux/OSX servers.

**Comment by sharpe5** [comment]
This library is almost ready to migrate from alpha to stable status. If you make the change and make a pull request, we will definitely approve it!

**Comment by sharpe5** [comment]
I'm using .NET Core now, so I'll look into closing this issue within a week or two. As always - a pull request will be accepted if anyone can beat me to it.

**Comment by sharpe5** [comment]
Have a pending pull request whichimplements support for .NET Core 1.0. NuGet package will be up within a day or two (ping me if you want it).

**Comment by sharpe5** [comment]
NuGet package 0.9.4-rc7 has support for NetStandard 1.6, .NET Core 1.0.1, and .NET 4.5 and up.
