### ISSUE TITLE
An old library still referenced

### ISSUE THREAD

**Issue by MikaelFerland** [NetMQ/NetMQ.ReactiveExtensions#45]
When you have a fresh install and just trying to install this package on runtime. You will get this error : **Could not load file or assembly 'System.Xml.Linq, Version=3.5.0.0,** because you are depending on a old library in the project.json file 
    ```"net45": {
      "dependencies": {
        "System.Xml.Linq": "3.5.*"
      }```
 Could you fix it please. I did something to work around, but I do not want to break thing.

**Comment by somdoron** [comment]
Can you make a pull request?
