### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by ChristianWeyer** [NetMQ/NetMQ.ReactiveExtensions#49]
:-)

**Comment by sharpe5** [comment]
Yes, its very much alive. Its currently deployed in a company with 500 employees as part of an Excel spreadsheet plugin which allows the entire development team to observe streaming data from a remarkably complex collection of data publishers. Although, to be fair, the version used there is the last checkin that was designed for .NET 4. The latest version in master is for .NET Core which is still quite experimental.
